package com.zzy.shardingjdbcdemo.dao;

import com.zzy.shardingjdbcdemo.po.T;
import java.util.List;

public interface TMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t
     *
     * @mbg.generated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t
     *
     * @mbg.generated
     */
    T selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t
     *
     * @mbg.generated
     */
    List<T> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T record);

    List<T> queryByOrder();

    List<T> queryBetween(Long id1, Long id2);

    void batchInsert(List<T> t);

}
