#开发配置
server:
  #默认端口
  port: 8017
  servlet:
    context-path: /demo
  tomcat:
    #tomcat-URI-编码
    uri-encoding: UTF-8
#日志配置
logging:
  level:
    com.zzy: debug
    org.springframework: WARN
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.166.65.174:3306/zzy?useUnicode=true&characterEncoding=utf8&&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    hikari:
      minimum-idle: 50
      maximum-pool-size: 50
  redis:
    database: 0
    timeout: 1000
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    password: mypassword
    host: 192.166.65.174
    port: 6379

#映射文件
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.zzy.shardingjdbcdemo.po
  configuration:
    map-underscore-to-camel-case: true