package com.zzy.shardingjdbcdemo.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t
 */
public class T {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t.a
     *
     * @mbg.generated
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t.b
     *
     * @mbg.generated
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t.c
     *
     * @mbg.generated
     */
    private Integer c;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t.id
     *
     * @return the value of t.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t.id
     *
     * @param id the value for t.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t.a
     *
     * @return the value of t.a
     *
     * @mbg.generated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t.a
     *
     * @param a the value for t.a
     *
     * @mbg.generated
     */
    public void setA(String a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t.b
     *
     * @return the value of t.b
     *
     * @mbg.generated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t.b
     *
     * @param b the value for t.b
     *
     * @mbg.generated
     */
    public void setB(String b) {
        this.b = b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t.c
     *
     * @return the value of t.c
     *
     * @mbg.generated
     */
    public Integer getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t.c
     *
     * @param c the value for t.c
     *
     * @mbg.generated
     */
    public void setC(Integer c) {
        this.c = c;
    }
}